In [ ]:
import phidown

In [20]:
from phidown.search import CopernicusDataSearcher
# You can modify these parameters as needed

searcher = CopernicusDataSearcher()
# Configure the search parameters
searcher.query_by_filter(
    collection_name='SENTINEL-1',
    product_type=None,
    orbit_direction=None,
    cloud_cover_threshold=None,
    aoi_wkt=None,
    start_date='2023-05-03T00:00:00',
    end_date='2024-05-03T04:00:00',
    top=1000,
    attributes={'processingLevel': 'LEVEL0',
                'operationalMode': 'SM'} 
)

df = searcher.execute_query()
print(f"Number of results: {len(df)}")
# Display the first few rows of the DataFrame
searcher.display_results(top_n=15)

Number of results: 910

,Id,Name,S3Path,GeoFootprint,OriginDate,Attributes
0,00cd06ea-80e6-4ee2-9fb3-b5c0ec189186,S1A_S6_RAW__0SDV_20240502T195132_20240502T1951...,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-24.5551...",2024-05-02 20:15:12,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
1,e68c7e10-7213-443e-857c-f9ddadb648fb,S1A_S4_RAW__0SDV_20240502T193657_20240502T1937...,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-12.4077...",2024-05-02 20:15:29,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
2,8f52959c-83d4-4568-8b9c-3bdc7933c14b,S1A_S1_RAW__0SDH_20240502T121147_20240502T1212...,/eodata/Sentinel-1/SAR/S1_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-88.2859...",2024-05-02 13:07:28,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
3,54192b79-3683-4234-82f6-78f154af2d1c,S1A_S4_RAW__0SDV_20240502T062925_20240502T0629...,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-177.858...",2024-05-02 07:16:16,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
4,c03e2735-12b5-47cd-9deb-af959af4aa55,S1A_S6_RAW__0SDV_20240502T055859_20240502T0559...,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-12.6051...",2024-05-02 07:16:24,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
5,787b9ec5-3220-47dc-89ab-0b3bf4fadf49,S1A_S6_RAW__0SDV_20240502T055256_20240502T0553...,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-5.7387,...",2024-05-02 07:16:26,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
6,104a0aa5-9e7f-46d4-bcbd-1013b2e5e317,S1A_S2_RAW__0SDV_20240502T014919_20240502T0149...,/eodata/Sentinel-1/SAR/S2_RAW__0S/2024/05/02/S...,"{'type': 'Polygon', 'coordinates': [[[-118.686...",2024-05-02 07:34:46,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
7,3ef3d6d3-c183-49b9-9ff1-db7a648989a8,S1A_S3_RAW__0SDH_20240430T213606_20240430T2136...,/eodata/Sentinel-1/SAR/S3_RAW__0S/2024/04/30/S...,"{'type': 'Polygon', 'coordinates': [[[-46.5147...",2024-04-30 22:23:23,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
8,910170c0-ac1d-4961-beb1-0a1418de3506,S1A_S1_RAW__0SDV_20240430T123135_20240430T1232...,/eodata/Sentinel-1/SAR/S1_RAW__0S/2024/04/30/S...,"{'type': 'Polygon', 'coordinates': [[[-95.3818...",2024-04-30 13:15:57,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
9,a858b079-7c24-430b-8bc2-aa415e29fcb7,S1A_S5_RAW__0SDV_20240429T200803_20240429T2008...,/eodata/Sentinel-1/SAR/S5_RAW__0S/2024/04/29/S...,"{'type': 'Polygon', 'coordinates': [[[145.7952...",2024-04-29 23:14:01,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
10,cc9c177e-8f0a-4d75-9fb4-8179450b3cf3,S1A_S5_RAW__0SDV_20240429T200738_20240429T2008...,/eodata/Sentinel-1/SAR/S5_RAW__0S/2024/04/29/S...,"{'type': 'Polygon', 'coordinates': [[[146.0728...",2024-04-29 23:14:01,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
11,344c53cf-2c6c-413d-addb-b49381512501,S1A_S4_RAW__0SDV_20240429T183639_20240429T1836...,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/04/29/S...,"{'type': 'Polygon', 'coordinates': [[[165.7602...",2024-04-29 19:28:40,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
12,98291972-58e9-424d-bdd9-d296039f0fdb,S1A_S1_RAW__0SDV_20240429T020729_20240429T0207...,/eodata/Sentinel-1/SAR/S1_RAW__0S/2024/04/29/S...,"{'type': 'Polygon', 'coordinates': [[[55.5908,...",2024-04-29 03:44:56,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
13,17cacfc1-6b67-49a8-8557-933be33c8d9f,S1A_S4_RAW__0SDH_20240428T234920_20240428T2349...,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/04/28/S...,"{'type': 'Polygon', 'coordinates': [[[-89.0942...",2024-04-29 00:15:49,"[{'@odata.type': '#OData.CSC.StringAttribute',..."
14,c69aa65a-a7de-420c-b010-8566c4fdc423,S1A_S3_RAW__0SSH_20240428T000116_20240428T0001...,/eodata/Sentinel-1/SAR/S3_RAW__0S/2024/04/28/S...,"{'type': 'Polygon', 'coordinates': [[[73.1747,...",2024-04-28 01:07:10,"[{'@odata.type': '#OData.CSC.StringAttribute',..."

In [21]:
df.iloc[0]['Name']

'S1A_S6_RAW__0SDV_20240502T195132_20240502T195153_053697_0685CC_E173.SAFE'

In [17]:
df = df[~df['Name'].str.contains('IW')]
df = df[~df['Name'].str.contains('EW')]

In [18]:
df

,@odata.mediaContentType,Id,Name,ContentType,ContentLength,OriginDate,PublicationDate,ModificationDate,Online,EvictionDate,S3Path,Checksum,ContentDate,Footprint,GeoFootprint,Attributes
220,application/octet-stream,00cd06ea-80e6-4ee2-9fb3-b5c0ec189186,S1A_S6_RAW__0SDV_20240502T195132_20240502T1951...,application/octet-stream,931203434,2024-05-02 20:15:12,2024-05-02T20:20:56.032842Z,2024-05-02T20:21:05.633321Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"[{'Value': '268e7dbf1588e52c293f1309d4910555',...","{'Start': '2024-05-02T19:51:32.488701Z', 'End'...",geography'SRID=4326;POLYGON ((-24.5551 14.1238...,"{'type': 'Polygon', 'coordinates': [[[-24.5551...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
221,application/octet-stream,e68c7e10-7213-443e-857c-f9ddadb648fb,S1A_S4_RAW__0SDV_20240502T193657_20240502T1937...,application/octet-stream,1445174835,2024-05-02 20:15:29,2024-05-02T20:22:09.198017Z,2024-05-02T20:22:22.241997Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/05/02/S...,"[{'Value': '6bee635de3702762dc1f261cce8383c6',...","{'Start': '2024-05-02T19:36:57.285667Z', 'End'...",geography'SRID=4326;POLYGON ((-12.4077 -38.561...,"{'type': 'Polygon', 'coordinates': [[[-12.4077...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
434,application/octet-stream,8f52959c-83d4-4568-8b9c-3bdc7933c14b,S1A_S1_RAW__0SDH_20240502T121147_20240502T1212...,application/octet-stream,1946129366,2024-05-02 13:07:28,2024-05-02T13:13:36.076821Z,2024-05-02T13:13:52.392367Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S1_RAW__0S/2024/05/02/S...,"[{'Value': '3d0de41da02dc0c1ac6aabe7368c4fae',...","{'Start': '2024-05-02T12:11:47.360207Z', 'End'...",geography'SRID=4326;POLYGON ((-88.2859 40.6066...,"{'type': 'Polygon', 'coordinates': [[[-88.2859...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
582,application/octet-stream,54192b79-3683-4234-82f6-78f154af2d1c,S1A_S4_RAW__0SDV_20240502T062925_20240502T0629...,application/octet-stream,1051289098,2024-05-02 07:16:16,2024-05-02T07:22:46.043310Z,2024-05-02T07:22:55.832289Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S4_RAW__0S/2024/05/02/S...,"[{'Value': '3fd1397a1066976b52cd7658e43858bf',...","{'Start': '2024-05-02T06:29:25.324425Z', 'End'...",geography'SRID=4326;POLYGON ((-177.858 -29.997...,"{'type': 'Polygon', 'coordinates': [[[-177.858...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
591,application/octet-stream,c03e2735-12b5-47cd-9deb-af959af4aa55,S1A_S6_RAW__0SDV_20240502T055859_20240502T0559...,application/octet-stream,1415443692,2024-05-02 07:16:24,2024-05-02T07:22:41.162260Z,2024-05-02T07:22:55.296515Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"[{'Value': 'ff69a0a73ceba99e8f7a069f7895d8da',...","{'Start': '2024-05-02T05:58:59.015465Z', 'End'...",geography'SRID=4326;POLYGON ((-12.6051 -38.864...,"{'type': 'Polygon', 'coordinates': [[[-12.6051...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
592,application/octet-stream,787b9ec5-3220-47dc-89ab-0b3bf4fadf49,S1A_S6_RAW__0SDV_20240502T055256_20240502T0553...,application/octet-stream,1442352167,2024-05-02 07:16:26,2024-05-02T07:22:41.927854Z,2025-09-21T02:07:12.592276Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S6_RAW__0S/2024/05/02/S...,"[{'Value': 'fdba87c3107919d275f2e93f5878c513',...","{'Start': '2024-05-02T05:52:56.785194Z', 'End'...",geography'SRID=4326;POLYGON ((-5.7387 -17.3872...,"{'type': 'Polygon', 'coordinates': [[[-5.7387,...","[{'@odata.type': '#OData.CSC.StringAttribute',..."
722,application/octet-stream,104a0aa5-9e7f-46d4-bcbd-1013b2e5e317,S1A_S2_RAW__0SDV_20240502T014919_20240502T0149...,application/octet-stream,1143705125,2024-05-02 07:34:46,2024-05-02T07:40:55.670660Z,2024-05-02T07:41:06.736639Z,True,9999-12-31T23:59:59.999999Z,/eodata/Sentinel-1/SAR/S2_RAW__0S/2024/05/02/S...,"[{'Value': 'd1c681d41a0a0301c0904b258444c170',...","{'Start': '2024-05-02T01:49:19.791817Z', 'End'...",geography'SRID=4326;POLYGON ((-118.6869 28.169...,"{'type': 'Polygon', 'coordinates': [[[-118.686...","[{'@odata.type': '#OData.CSC.StringAttribute',..."

In [19]:
df.iloc[0]['Attributes']

[{'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'origin',
  'Value': 'ESA',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'datatakeID',
  'Value': 427468,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'cycleNumber',
  'Value': 321,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'orbitNumber',
  'Value': 53697,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'sliceNumber',
  'Value': 1,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'productClass',
  'Value': 'S',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'orbitDirection',
  'Value': 'ASCENDING',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.DateTimeOffsetAttribute',
  'Name': 'processingDate',
  'Value': '2024-05-02T20:13:41.753139Z',
  'ValueType': 'DateTimeOffset'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'operationalMode',
  'Value': 'SM',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'processingLevel',
  'Value': 'LEVEL0',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'swathIdentifier',
  'Value': '6',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'processingCenter',
  'Value': 'S1 Production Service-SERCO',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.BooleanAttribute',
  'Name': 'sliceProductFlag',
  'Value': False,
  'ValueType': 'Boolean'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'platformShortName',
  'Value': 'SENTINEL-1',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'instrumentShortName',
  'Value': 'SAR',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'relativeOrbitNumber',
  'Value': 75,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'polarisationChannels',
  'Value': 'VH&VV',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'productConsolidation',
  'Value': 'SLICE',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'platformSerialIdentifier',
  'Value': 'A',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.IntegerAttribute',
  'Name': 'instrumentConfigurationID',
  'Value': 7,
  'ValueType': 'Integer'},
 {'@odata.type': '#OData.CSC.DoubleAttribute',
  'Name': 'startTimeFromAscendingNode',
  'Value': 222314.36,
  'ValueType': 'Double'},
 {'@odata.type': '#OData.CSC.DoubleAttribute',
  'Name': 'completionTimeFromAscendingNode',
  'Value': 242954.848,
  'ValueType': 'Double'},
 {'@odata.type': '#OData.CSC.StringAttribute',
  'Name': 'productType',
  'Value': 'S6_RAW__0S',
  'ValueType': 'String'},
 {'@odata.type': '#OData.CSC.DateTimeOffsetAttribute',
  'Name': 'beginningDateTime',
  'Value': '2024-05-02T19:51:32.488701Z',
  'ValueType': 'DateTimeOffset'},
 {'@odata.type': '#OData.CSC.DateTimeOffsetAttribute',
  'Name': 'endingDateTime',
  'Value': '2024-05-02T19:51:53.129189Z',
  'ValueType': 'DateTimeOffset'}]